### ISSUE TITLE
NSL-KDD dataset

### ISSUE THREAD

**Issue by yjnanan** [JXYin24/MCM#1]
Hi authors,

I appreciate your excellent work. When I reproduced your work, I found that the NSL-KDD dataset can't be found in ADBench and ODDS. Could you please provide this dataset? Thanks!

**Comment by JXYin24** [comment]
You can download this dataset in https://github.com/yj-zhou/Feature_Encoding_with_AutoEncoders_for_Weakly-supervised_Anomaly_Detection/tree/main/dataset

**Comment by yjnanan** [comment]
Thanks!
