### ISSUE TITLE
Results miss match

### ISSUE THREAD

**Issue by yjnanan** [JXYin24/MCM#3]
Hi authors,

I appreciate your excellent work. When I read your paper, I found that the results of your baseline in Table 1 do not match the results in Figure 4 (AUC-PR). I mean the results when the anomaly contamination rate is 0%. Is that a mistake?
![image](https://github.com/user-attachments/assets/c63ef0fe-0162-4620-bc6c-e8e4a364f8a2)
![image](https://github.com/user-attachments/assets/6056e8aa-ee70-45ab-a47e-4a52ea6c2179)

**Comment by JXYin24** [comment]
Thank you for your recognition. Our settings assume that there is 2% contamination in the data set by default. So,  the results in Table 1 are calculated when the anomaly contamination rate is 2%

**Comment by yjnanan** [comment]
Do you mean the results in Table 1 are calculated when the anomaly contamination rate is 2%? However, you did not describe this in your evaluation metrics subsection. And I don't find corresponding codes in your published code.
![image](https://github.com/user-attachments/assets/623a5b7c-0fdd-4da7-a88f-38d48075fa5f)

**Comment by yjnanan** [comment]
Thanks for your explanation. Could you please provide your results with 0% anomaly contamination rate? Thank you very much!

**Comment by yjnanan** [comment]
> Thank you for your recognition. Our settings assume that there is 2% contamination in the data set by default. So, the results in Table 1 are calculated when the anomaly contamination rate is 2%

Hi authors,

Thanks for your explanation. You mean the results in Table 1 of the published paper are obtained when the anomaly contamination rate is 2%. Your evaluation metrics subsection said, "The training dataset consists of one-half of the normal data, while the testing dataset comprises the other half of the normal data combined with all the abnormal instances." The description of your evaluation metrics indicates that you conduct experiments under the setting of 0% anomaly contamination rate. Additionally, assuming that the results of Table 1 are calculated when the anomaly contamination rate is 2%, which still don't match the results in Figure 4 (AUC-PR). In my opinion, this is a serious problem. I want to follow your work for research, and I hope you can clarify this. Thanks!
![image](https://github.com/user-attachments/assets/0864f513-b9bb-4544-bd20-4a5cf3b26ded)
![image](https://github.com/user-attachments/assets/7795a1ab-301b-4008-8774-dfaaa2b46d81)
![image](https://github.com/user-attachments/assets/c2bfc614-8d24-4f40-8dec-0966101c913b)
